core/urls.py
from django.urls import path
from .views import (index, contact_view, dashboard_view, profile_settings_view, 
                    profile_view, plan_detail_view, send_payment_review, 
                    plans_view,deposit_view,send_deposit_review,transaction_view,deposits_view,search_view,withdraw_view,withdrawal_view,faq,about,referral_view)

app_name = "core"

urlpatterns = [
    path('', index, name='index'),
    path('home/', index, name='index'),
    path('contact', contact_view, name='contact'),
    path('faq', faq, name='faq'),
    path('about', about, name='about'),
    path('app/dashboard',dashboard_view, name='dashboard'),
    path('app/dashboard/',dashboard_view, name='dashboard'),
    path('app/deposit',deposit_view, name='deposit'),
    path('app/deposit/payment/',send_deposit_review, name='payment'),
    path('app/deposit/payment',send_deposit_review, name='payment'),
    path('app/profile-settings', profile_settings_view, name='profile-settings'),
    path('app/profile', profile_view, name='profile'),
    path('app/plan/<pid>/', plan_detail_view, name='plan-detail'),
    path('app/plans', plans_view, name='plans'),
    path('app/transactions', transaction_view, name='transactions'),
    path('app/deposits', deposits_view, name='deposits'),
    path('app/referrals', referral_view, name='referrals'),
    path('app/withdraw', withdraw_view, name="withdraw"),
    path('app/withdrawals', withdrawal_view, name="withdrawals"),
    path("send-payment-review/<pid>/", send_payment_review, name="send-payment-review"),
    path('search/', search_view, name='search'),



]

userauths/urls.py
from django.urls import path, include
from userauths import views, utils

app_name = "userauths"

urlpatterns = [
    path('user/sign-up/', views.register_view, name= "sign-up"),
    path('sign-up/', views.referral_signup, name='referral-signup'),
    path('user/sign-in/', views.login_view, name="sign-in"),
    path('user/forgot-password/', views.forgot_password, name="forgot-password"),
    path('get_user_data/', views.get_user_data, name='get_user_data'),
    path('trigger_daily_task/', views.trigger_daily_task, name='trigger_daily_task'),
    path('get_total_deposit/', views.get_total_deposit, name='get_total_deposit'),
    path('confirm-email/<str:token>/', utils.confirm_email, name='confirm_email'),
    path('email-confirmed/', views.email_confirmed, name="email_confirmed"),
    path('invalid-token/', views.email_invalid, name="invalid_token"),
    path('reset-password/<str:token>/', views.password_reset_form, name='password_reset_form'),
    path('process-password-reset/', views.process_password_reset, name='process_password_reset'),
    path('user/send-password-reset-email/', views.send_password_reset, name='send-password-reset-email'),
    path('password-reset-success/', views.password_reset_success, name="password-reset-success"),
    path('logout', views.logout_view, name="logout"),
    path('lockscreen', views.lock_screen_view, name='lockscreen'),
]

vanguardfx/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.urls import re_path as url
from django.views.static import serve
from django.views.decorators.csrf import csrf_exempt

admin.autodiscover()
admin.site.login = csrf_exempt(admin.site.login)
urlpatterns = [
    url(r'^media/(?P<path>.*)$', serve,{'document_root': settings.MEDIA_ROOT}),

    url(r'^static/(?P<path>.*)$', serve,{'document_root': settings.STATIC_ROOT}),
    path("admin/", admin.site.urls),
    path("", include("core.urls")),
    path("", include("userauths.urls"))
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)



handler404 = 'core.views.custom_error_page'
handler403 = 'core.views.custom_error_page2'
handler500 = 'core.views.custom_error_page1'

userauths/views.py
from django.shortcuts import render,redirect
from userauths.forms import UserRegisterForm
from django.contrib.auth import login, authenticate
from django.contrib import messages
from django.contrib.auth import logout
from userauths.models import User
import resend
from django.http import JsonResponse
from .models import Deposit
from django.db.models import Sum
from userauths.models import Transaction
from django.utils import timezone
from .models import UserToken
from .utils import send_confirmation_email, reset_password
from django.contrib.auth.hashers import make_password
from django.db import transaction as ts
from django.conf import settings
resend.api_key = getattr(settings, 'SENSITIVE_VARIABLE', None)

def perform_daily_task():
    try:
        current_time = timezone.now()

        # Fetch only the transactions that are not processed yet
        transactions = Transaction.objects.filter(plan_interval_processed=False, confirmed=True)

        for transaction in transactions:
            time_difference = current_time - transaction.timestamp
            if int(transaction.interval_count) < int(transaction.convert_description_to_days()) and (time_difference.days >= transaction.days_count):
               
                 
                    amount_to_add = transaction.percentage_return * transaction.amount / 100
                
                    # Update the user's total_invested field
                    transaction.user.total_invested += amount_to_add
                    transaction.user.save()
 
                    # Update interval_count and days_count
                    transaction.interval_count += 1
                    transaction.days_count += 1

                    # Save all changes at once
                    transaction.save(update_fields=['interval_count', 'days_count'])

            # elif transaction.interval_count >= 7:
                
            #     # Move total_invested to total_deposit
            #     transaction.user.total_deposit += transaction.user.total_invested
            #     transaction.user.total_invested = 0
            #     transaction.user.save(update_fields=['total_deposit', 'total_invested'])

            #     # Set plan_interval_processed to True
            #     transaction.plan_interval_processed = True
            #     transaction.save()

            elif time_difference.days >= int(transaction.convert_description_to_days()):
                 # Move total_invested to total_deposit
                transaction.user.total_deposit += transaction.user.total_invested
                transaction.user.total_invested = 0
                transaction.user.save(update_fields=['total_deposit', 'total_invested'])

                # Set plan_interval_processed to True
                transaction.plan_interval_processed = True
                transaction.save()
            else: 
                pass



    except Exception as e:
        print(f"Error in perform_daily_task: {e}")



def register_view(request):
    pre_filled_email = request.session.get('pre_filled_email', '')
    form = UserRegisterForm(initial={'email': pre_filled_email})
    if request.method == "POST":
        address = request.POST['address']
        username = request.POST['username']
        form = UserRegisterForm(request.POST or None)
        
        if form.is_valid():
            
            new_user = form.save(commit=False)  # Don't save the user yet
            new_user.email_verified = False
            new_user.save()
            send_confirmation_email(request, new_user)
            
            username = form.cleaned_data.get("username")
            email = form.cleaned_data.get('email')
            messages.success(request, f"Hey {username}, an email a confirmation email has been sent")

            new_user = authenticate(username=form.cleaned_data['email'],
                                    password=form.cleaned_data['password1']
            )
         
          
            try:
                r = resend.Emails.send({
                    "from": "Cryptovest <support@cryptovest.online>",
                    "to": 'cryptovest741@gmail.com',
                    "subject": "New User",
                    "html": f"""
                        <!DOCTYPE html>
                        <html lang="en">
                        
                        <body>
                            <div class="container">
                                <h1>Hey Admin,<br> Someone created an account !</h1>
                                <p>A new user with the name {username} and email {email} signed up to Cryptovest.</p>
                                <p>Check them out, they can be potential clients</p>
                                <p>Login to your admin panel to view them:</p><br><br>
                                <div style="text-align: center; align-items: center;">
                                    <a href="https://cryptovest.online/admin/userauths/user/" class="btn btn-primary" style="background-color: #007bff; font-size: 16px; border-color: #007bff; padding: 10px 20px; border-radius: 2px;" target="_blank">Admin Panel</a><br><br>
                                </div>
                                
                            </div>
                        </body>
                        </html>
                    """,
                })
    
            except Exception as e:
                pass

   

            return redirect("core:dashboard")
    context = {
        'form': form,
        
    }
    return render(request, 'userauths/sign-up.html', context)

def referral_signup(request):
    ref = request.GET.get('ref')
    form = UserRegisterForm()
    if request.method == "POST":
        username = request.POST['username']
        form = UserRegisterForm(request.POST or None)
        
        if form.is_valid():
            
            new_user = form.save(commit=False)  # Don't save the user yet
            new_user.email_verified = False
            new_user.save()
            send_confirmation_email(request, new_user)
            
            username = form.cleaned_data.get("username")
            email = form.cleaned_data.get('email')
            messages.success(request, f"Hey {username}, an email a confirmation email has been sent")
            new_user = authenticate(username=form.cleaned_data['email'],
                                    password=form.cleaned_data['password1']
            )
            try:
                r = resend.Emails.send({
                    "from": "Cryptovest <support@cryptovest.online>",
                    "to": 'hello@cryptovest.online',
                    "subject": "New User",
                    "html": f"""
                        <!DOCTYPE html>
                        <html lang="en">
                    
                        <body>
                            <div class="container">
                                <h1>Hey Admin,<br> Someone created an account !</h1>
                                <p>A new user with the name {username} and email {email} signed up to Cryptovest.</p>
                                <p>Check them out, they can be potential clients</p>
                                <p>Login to your admin panel to view them:</p><br><br>
                                <div style="text-align: center; align-items: center;">
                                    <a href="https://cryptovest.online/admin/userauths/user/" class="btn btn-primary" style="background-color: #007bff; color: #fff; font-size: 16px; border-color: #007bff; padding: 10px 20px; border-radius: 2px;" target="_blank">Admin Panel</a><br><br>
                                </div>
                                
                            </div>

                        
                        </body>
                        </html>
                    """,
                })
            except Exception as e:
                pass
  
            

   

            return redirect("core:dashboard")
        
    if ref:
        form.fields['referred'].initial = ref
    context = {
        'form': form,
    }
    return render(request, 'userauths/sign-up.html', context)


def login_view(request):
    if request.user.is_authenticated:
        return redirect("core:index")
    if request.method == "POST":
        email = request.POST.get('email')
        password = request.POST.get('password')

        try:
            user = User.objects.get(email=email)
            user = authenticate(request, email=email, password=password)
            if user is not None:
                login(request, user)
                perform_daily_task()
                messages.success(request, "Successfully logged in.")
                return redirect("core:dashboard")
            else:
                messages.warning(request, "Invalid credentials, create an account.")
        except:
            messages.warning(request, f"User does not exist")


    return render(request, 'userauths/sign-in.html' )





def get_user_data(request):
    # Retrieve the current user
    current_user = request.user

    # Fetch data for the current user
    if current_user.is_authenticated:
        data = {
            'total_invested': str(current_user.total_invested),
            'total_deposit': str(current_user.total_deposit),
            # Add other fields as needed
        }
        return JsonResponse(data)


def get_total_deposit(request):
    # Retrieve the current user
    user = request.user
    confirmed_deposits = Deposit.objects.filter(user=user, confirmed=True)
    valid_transactiions = Transaction.objects.filter(user=user)
    total_transactions = valid_transactiions.aggregate(total_amount=Sum('amount'))['total_amount'] or 0
    total_deposits = confirmed_deposits.aggregate(total_amount=Sum('amount'))['total_amount'] or 0

    # Fetch data for the current user
    if user.is_authenticated:
        data = {
            'total_deposits': str(total_deposits),

templates/userauths/sign-in.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1, minimum-scale=1.0, shrink-to-fit=no">
  <link href="{% static "favicon/favicon.ico" %}" rel="icon">
  <title>Sign In - DigtalTradez</title>
  <meta name="description" content="DigtalTradez Login, Sign In, Login">
  <meta name="author" content="DigtalTradez">
  <meta content="DigtalTradez - The best platform to invest in Forex and Defi" name="description" />
  <link rel="apple-touch-icon" sizes="180x180" href="{% static "favicon/apple-touch-icon.png" %}">
	<link rel="icon" type="image/png" sizes="32x32" href="{% static "favicon/favicon-32x32.png" %}">
	<link rel="icon" type="image/png" sizes="16x16" href="{% static "favicon/favicon-16x16.png" %}">
	<link rel="manifest" href="{% static "favicon/site.webmanifest" %}">
 <link rel="shortcut icon" href="{% static 'favicon/favicon-32x32.png' %}">

  <!-- Web Fonts
========================= -->
  <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Poppins:100,200,300,400,500,600,700,800,900"
    type="text/css">

  <!-- Stylesheet
    
========================= -->
<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Poppins&display=swap" rel="stylesheet">
  <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.min.css' %}">
  <link rel="stylesheet" type="text/css" href="{% static 'css/all.min.css' %}">

</head>

<body>
  <style>
    body{
      font-family: 'Poppins', sans-serif;
    }
  </style>



  <div id="main-wrapper" class="oxyy-login-register">
    <div class="hero-wrap d-flex align-items-center">
      <div class="hero-mask opacity-4 bg-secondary"></div>
      <div class="hero-bg hero-bg-scroll" ></div>
      <div class="hero-content w-100" style="background: #fff">
        <div class="container">
          <div class="row g-0 min-vh-100">
            <!-- Welcome Text
		  ========================= -->
            <div class="col-md-6 d-flex flex-column">
              <div class="row g-0 my-auto">
                <style>
                  
                  @media (max-width: 768px) {
                    .disp-none {display: none;}
                  }
                  
                </style>
                <div class="col-11 col-sm-10 col-lg-9 mx-auto text-center disp-none"  >
                  <div class="logo mt-5 mb-3"> 
                    <a href="/" title="CryptoVest">
    
                    </a> 
                      </div>
          
                </div>
              </div>
            </div>
            <!-- Welcome Text End -->






            <!-- Login Form
		  ========================= -->
            <div class="col-md-6 d-flex align-items-center py-5 " >
              <div class="container my-auto py-4 shadow-lg bg-white">
                <div class="row">
                  <div class="col-11 col-lg-10 mx-auto">
                    <div class="  d-flex justify-content-center align-items-center" >
                      {% comment %} <img src="{% static 'logo/logo-2.png' %}" height="30" alt="DigtalTradez">  {% endcomment %}
                    </div>
                    <h3 class="text-9 fw-600 text-center my-3">Sign In</h3>
                    
                        {% if messages %}
                        {% for message in messages %}
                            <div class="alert alert-{{message.tags}}">
                                <strong>{{ message }}</strong>
                            </div>

                        {% endfor %}
                    {% endif %}
                    <script>
                        setTimeout (() => {
                            $(".alert").alert("close");
                        }, 5000)
                    </script>   
                    <form id="loginForm" method="POST">
                      {% csrf_token %}
                      <div class="mb-3">
                        <label class="form-label text-dark fw-600" for="emailAddress">Email Address</label>
                        <input type="email" name="email" class="form-control rounded-2" id="emailAddress" required=""
                          placeholder="Enter Your Email">
                      </div>
                      <div class="mb-3">
                        <label class="form-label text-dark fw-600" for="loginPassword">Password</label>
                        <div class="input-group">
                            <input type="password" name="password" class="form-control rounded-2" id="loginPassword" required="" placeholder="Enter Password">
                            <button type="button" class="btn btn-outline-secondary" style="border: 1px solid silver; " id="togglePassword">
                                <i class="fas fa-eye" id="eye-icon"></i>
                            </button>
                        </div>
                      </div>
                    <script>
                      const passwordInput = document.getElementById('loginPassword');
                      const toggleButton = document.getElementById('togglePassword');
                      const eyeIcon = document.getElementById('eye-icon');
                  
                      toggleButton.addEventListener('click', function () {
                          if (passwordInput.type === 'password') {
                              passwordInput.type = 'text';
                              eyeIcon.classList.remove('fa-eye');
                              eyeIcon.classList.add('fa-eye-slash');
                          } else {
                              passwordInput.type = 'password';
                              eyeIcon.classList.remove('fa-eye-slash');
                              eyeIcon.classList.add('fa-eye');
                          }
                      });
                  </script>
                      <div class="row mt-4" style="text-align: right;">
                        <div class="col">
                        
                            
                      <a href="{% url "userauths:forgot-password" %}" class="fw-semibold" style="text-decoration: none; color: #000;" >Forgot password?</a> 
                          
                        </div>
                      </div>
                      <div class="d-grid my-4">
                        <button style="background:#1235b4; color: #fff;" class="btn rounded-2" type="submit">Sign In</button>
                      </div>
                      <p class="text-center mb-4">I don't have an account yet?  <a
                        style="color: #1235b4; text-decoration: none; font-weight: 500;" href="{% url "userauths:sign-up" %}">Create an Account</a></p>
                    </form>


                  </div>
                </div>
              </div>
            </div>
            <!-- Login Form End -->
          </div>
        </div>
      </div>
    </div>
  </div>

  <!-- Styles Switcher -->
  <!-- Styles Switcher End -->

  <!-- Script -->
  <script src="{% static 'js/jquery.min.js' %}"></script>
  <script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>
  <script src="{% static 'js/theme.js' %}"></script>

</body>

</html>

templates/userauths/sign-up.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1, minimum-scale=1.0, shrink-to-fit=no">
  <link href="{% static "favicon/favicon.ico" %}" rel="icon">
  <title>Sign Up - DigtalTradez</title>
  <meta name="description" content="DigtalTradez Login, Sign Up, Create Account">
  <meta name="author" content="DigtalTradez">
  <meta content="DigtalTradez - The best platform to invest in Forex and Defi" name="description" />
  <link rel="apple-touch-icon" sizes="180x180" href="{% static "favicon/apple-touch-icon.png" %}">
	<link rel="icon" type="image/png" sizes="32x32" href="{% static "favicon/favicon-32x32.png" %}">
	<link rel="icon" type="image/png" sizes="16x16" href="{% static "favicon/favicon-16x16.png" %}">
	<link rel="manifest" href="{% static "favicon/site.webmanifest" %}">
 <link rel="shortcut icon" href="{% static 'favicon/favicon-32x32.png' %}">
  <!-- Web Fonts
========================= -->
  <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Poppins:100,200,300,400,500,600,700,800,900"
    type="text/css">

  <!-- Stylesheet
========================= -->
<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Poppins&display=swap" rel="stylesheet">
  <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.min.css' %}">
  <link rel="stylesheet" type="text/css" href="{% static 'css/all.min.css' %}">
</head>

<body>
  <style>
    body{
      font-family: 'Poppins', sans-serif;
    }
  </style>

  <!-- Preloader -->

  <!-- Preloader End -->

  <div id="main-wrapper" class="oxyy-login-register">
    <div class="hero-wrap d-flex align-items-center">
      <div class="hero-mask opacity-4 bg-secondary"></div>
      <div class="hero-bg hero-bg-scroll" ></div>
      <div class="hero-content w-100" style="background: #fff">
        <div class="container">
          <div class="row g-0 min-vh-100">
            <!-- Welcome Text
		  ========================= -->
            <div class="col-md-6 d-flex flex-column">
              <div class="row g-0 my-auto">
                <style>
                  
                  @media (max-width: 768px) {
                    .disp-none {display: none;}
                  }
                  
                </style>
                
              </div>
            </div>
            <!-- Welcome Text End -->
          <!-- Register Form
		  ========================= -->
          <div class="col-md-6 d-flex justify-content-center align-items-center py-5 ">
            <div class="container my-auto py-4 shadow-lg bg-white">
              <div class="row">
                <div class="col-11 col-lg-10 mx-auto">
                  <div class="  d-flex justify-content-center align-items-center" >
                 </div>
                  <h3 class="text-9 fw-600 text-center my-3">Create an Account</h3>
                  
                  <div class="padding_eight_all bg-white">
                    {% if form.errors %}
                    <div class="alert alert-danger">
                        <strong style="font-size: 13px;">{{form.errors}}</strong>
                    </div>
                    {% endif %}
                </div>
                <script>
                    setTimeout (() => {
                        $(".alert").alert("close");
                    }, 4000)
              </script>
                  <form id="registerForm" method="POST">
                    {% csrf_token %}
                    <div class="mb-3">
                      
                      {{form.email}}
                    </div>
                    <div class="mb-3">
                      <label class="form-label text-dark fw-600" for="emailAddress">Username</label>
                      {{form.username}}
                    </div>
                    <div class="mb-3">
                      <label class="form-label text-dark fw-600" for="emailAddress">Phone</label>
                      {{form.contact}}
                    </div>
                    <div class="mb-3">
                      <label class="form-label text-dark fw-600" for="emailAddress">Country</label>
                      {{form.address}}
                    </div>
                    <div class="mb-3">
                      <label class="form-label text-dark fw-600" for="loginPassword">Password</label>
                      <div class="input-group">
                          {{ form.password1 }}
                          <button type="button" class="btn btn-outline-secondary" style="border: 1px solid silver; " id="togglePassword">
                              <i class="fas fa-eye" id="eye-icon"></i>
                          </button>
                      </div>
                  </div>
                  <div class="mb-3">
                      <label class="form-label text-dark fw-600" for="confirmPassword">Confirm Password</label>
                      <div class="input-group">
                          {{ form.password2 }}
                          <button type="button" class="btn btn-outline-secondary" style="border: 1px solid silver; " id="toggleConfirmPassword">
                              <i class="fas fa-eye" id="eye-icon-confirm"></i>
                          </button>
                      </div>
                  </div>
                  
                    <div class="mb-3">
                      <label class="form-label text-dark fw-600" for="loginPassword">Referral Code</label>
                      {{form.referred}}
                    </div>
                    <script>
                      const passwordInput = document.getElementById('{{ form.password1.id_for_label }}');
                      const confirmPasswordInput = document.getElementById('{{ form.password2.id_for_label }}');
                      const togglePasswordButton = document.getElementById('togglePassword');
                      const toggleConfirmPasswordButton = document.getElementById('toggleConfirmPassword');
                      const eyeIcon = document.getElementById('eye-icon');
                      const eyeIconConfirm = document.getElementById('eye-icon-confirm');
                  
                      togglePasswordButton.addEventListener('click', function () {
                          togglePasswordVisibility(passwordInput, eyeIcon);
                      });
                  
                      toggleConfirmPasswordButton.addEventListener('click', function () {
                          togglePasswordVisibility(confirmPasswordInput, eyeIconConfirm);
                      });
                  
                      function togglePasswordVisibility(inputField, icon) {
                          if (inputField.type === 'password') {
                              inputField.type = 'text';
                              icon.classList.remove('fa-eye');
                              icon.classList.add('fa-eye-slash');
                          } else {
                              inputField.type = 'password';
                              icon.classList.remove('fa-eye-slash');
                              icon.classList.add('fa-eye');
                          }
                      }
                  </script>
                    <div class="d-grid my-4">
						<button class="g-recaptcha btn rounded-2"  
            data-sitekey="reCAPTCHA_site_key" 
            data-callback='onSubmit' 
            data-action='submit'  style="background: #1235b4; color: #fff;" type="submit">Create Account</button>
					</div>
          <p class="text-center mb-4">Already have an account? <a style="color: #1235b4; text-decoration: none; font-weight: 500;" href="{% url "userauths:sign-in" %}">Login Here</a></p>
                  </form>

                </div>
              </div>
            </div>
          </div>

        </div>
      </div>
    </div>
  </div>
</div>

<!-- Styles Switcher -->
<!-- Styles Switcher End -->

<!-- Script -->
<script src="{% static 'js/jquery.min.js' %}"></script>
<script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>
<script src="{% static 'js/theme.js' %}"></script>

</body>

</html>